In [1]:
import pandas as pd
import random

df = pd.DataFrame(index=['09:00', '10:30', '12:00', '01:00', '02:30', '04:00'], columns=['월', '화', '수', '목', '금'])
df

         월    화    수    목    금
09:00  NaN  NaN  NaN  NaN  NaN
10:30  NaN  NaN  NaN  NaN  NaN
12:00  NaN  NaN  NaN  NaN  NaN
01:00  NaN  NaN  NaN  NaN  NaN
02:30  NaN  NaN  NaN  NaN  NaN
04:00  NaN  NaN  NaN  NaN  NaN

In [67]:
# 기본틀

import pandas as pd
import random

# 과목 리스트를 만듭니다.
subjects = ['확률과통계/고선우', '딥러닝/고선우', 'AI알고리즘/권수태', '기계학습/권수태', 'AI수학/민정익', '논리적문제해결/민정익', 
            '인공지능기초/이근호', '서비스러닝/이근호', '논리적문제해결/송주환', '영상이해/송주환', 'AI프로그래밍/김영수', 
            '리눅스운영체제/김영수']

# 시간대 리스트를 만듭니다.
time_slots = ['09:00', '10:30', '12:00', '01:00', '02:30', '04:00']

# 무작위로 시간표를 생성합니다.
timetable = pd.DataFrame(index=time_slots, columns=['월', '화', '수', '목', '금'])

for day in timetable.columns:
    for time in timetable.index:
        subject = random.choice(subjects)
        timetable.loc[time, day] = subject

# 생성된 시간표를 출력합니다.
timetable

                 월            화            수            목            금
09:00    확률과통계/고선우  리눅스운영체제/김영수  리눅스운영체제/김영수    확률과통계/고선우    서비스러닝/이근호
10:30      딥러닝/고선우     기계학습/권수태    확률과통계/고선우      딥러닝/고선우      딥러닝/고선우
12:00      딥러닝/고선우    서비스러닝/이근호     영상이해/송주환  논리적문제해결/송주환  논리적문제해결/민정익
01:00  AI프로그래밍/김영수    서비스러닝/이근호  리눅스운영체제/김영수  리눅스운영체제/김영수      딥러닝/고선우
02:30      딥러닝/고선우     영상이해/송주환   AI알고리즘/권수태   인공지능기초/이근호   인공지능기초/이근호
04:00    확률과통계/고선우      딥러닝/고선우  논리적문제해결/민정익      딥러닝/고선우      딥러닝/고선우

In [69]:
# 진로탐색 추가

import pandas as pd
import random

# 과목 리스트를 만듭니다.
subjects = ['확률과통계/고선우', '딥러닝/고선우', 'AI알고리즘/권수태', '기계학습/권수태', 'AI수학/민정익', '논리적문제해결/민정익', 
            '인공지능기초/이근호', '서비스러닝/이근호', '논리적문제해결/송주환', '영상이해/송주환', 'AI프로그래밍/김영수', 
            '리눅스운영체제/김영수']

# 시간대 리스트를 만듭니다.
time_slots = ['09:00', '10:30', '12:00', '01:00', '02:30', '04:00']

# 무작위로 시간표를 생성합니다.
timetable = pd.DataFrame(index=time_slots, columns=['월', '화', '수', '목', '금'])

for day in timetable.columns:
    for time in timetable.index:
        subject = random.choice(subjects)
        timetable.loc[time, day] = subject

# '진로탐색' 과목을 추가할 요일과 시간 설정
day_to_add = '수'
time_to_add = '04:00'

# 해당 요일과 시간에 '진로탐색' 과목을 추가
timetable.loc[time_to_add, day_to_add] = '진로탐색'

# 수정된 시간표를 출력
timetable

                 월            화            수            목            금
09:00  리눅스운영체제/김영수    서비스러닝/이근호  리눅스운영체제/김영수     영상이해/송주환     AI수학/민정익
10:30     AI수학/민정익   AI알고리즘/권수태     영상이해/송주환     영상이해/송주환   AI알고리즘/권수태
12:00  논리적문제해결/송주환    서비스러닝/이근호   AI알고리즘/권수태    서비스러닝/이근호      딥러닝/고선우
01:00     기계학습/권수태     영상이해/송주환  논리적문제해결/송주환    확률과통계/고선우   인공지능기초/이근호
02:30     기계학습/권수태  리눅스운영체제/김영수  리눅스운영체제/김영수  리눅스운영체제/김영수  논리적문제해결/송주환
04:00    서비스러닝/이근호    서비스러닝/이근호         진로탐색   인공지능기초/이근호  논리적문제해결/송주환

In [74]:
#점심시간과 진로탐색 추가

import pandas as pd
import random

# 과목 리스트를 만듭니다.
subjects = ['확률과통계/고선우', '딥러닝/고선우', 'AI알고리즘/권수태', '기계학습/권수태', 'AI수학/민정익', '논리적문제해결/민정익', '인공지능기초/이근호', '서비스러닝/이근호', '논리적문제해결/송주환', '영상이해/송주환', 'AI프로그래밍/김영수', '리눅스운영체제/김영수']

# 시간대 리스트를 만듭니다.
time_slots = ['09:00', '10:30', '12:00', '01:00', '02:30', '04:00']

# 무작위로 시간표를 생성합니다.
timetable = pd.DataFrame(index=time_slots, columns=['월', '화', '수', '목', '금'])

for day in timetable.columns:
    for time in timetable.index:
        if time == '12:00':
            timetable.loc[time, day] = "점심시간"
        elif day == '수' and time == '04:00':
            timetable.loc[time, day] = "진로탐색"
        else:
            subject = random.choice(subjects)
            timetable.loc[time, day] = subject

# 생성된 시간표를 출력합니다.
timetable

                 월            화            수            목            금
09:00  리눅스운영체제/김영수  논리적문제해결/송주환   AI알고리즘/권수태      딥러닝/고선우  AI프로그래밍/김영수
10:30  리눅스운영체제/김영수   AI알고리즘/권수태     기계학습/권수태     영상이해/송주환     영상이해/송주환
12:00         점심시간         점심시간         점심시간         점심시간         점심시간
01:00      딥러닝/고선우    확률과통계/고선우    서비스러닝/이근호     영상이해/송주환  리눅스운영체제/김영수
02:30    서비스러닝/이근호   인공지능기초/이근호  리눅스운영체제/김영수  리눅스운영체제/김영수  논리적문제해결/송주환
04:00     AI수학/민정익    확률과통계/고선우         진로탐색  논리적문제해결/송주환  AI프로그래밍/김영수

In [84]:
#2번씩만 나오도록 set으로 설정

import pandas as pd
import random

# 과목 리스트를 만듭니다.
subjects = ['확률과통계/고선우', '딥러닝/고선우', 'AI알고리즘/권수태', '기계학습/권수태', 
            'AI수학/민정익', '논리적문제해결1/민정익', '인공지능기초/이근호', '서비스러닝/이근호',
            '논리적문제해결2/송주환', '영상이해/송주환', 'AI프로그래밍/김영수', '리눅스운영체제/김영수']

# 시간대 리스트를 만듭니다.
time_slots = ['09:00', '10:30', '12:00', '01:00', '02:30', '04:00']

# 무작위로 시간표를 생성합니다.
timetable = pd.DataFrame(index=time_slots, columns=['월', '화', '수', '목', '금'])

# 중복 없이 과목을 배정하기 위한 set
subject_set = set()

for day in timetable.columns:
    for time in timetable.index:
        if time == '12:00':
            timetable.loc[time, day] = "점심시간"
        elif day == '수' and time == '04:00':
            timetable.loc[time, day] = "진로탐색"
        else:
            if not subject_set:  # set이 비어있을 경우, 모든 과목이 다 사용되었음
                subject_set = set(subjects)  # 모든 과목 다시 추가
            subject = random.choice(list(subject_set))
            subject_set.remove(subject)
            timetable.loc[time, day] = subject

# 생성된 시간표를 출력합니다.
timetable

                 월             화            수             목             금
09:00   AI알고리즘/권수태    인공지능기초/이근호    서비스러닝/이근호      AI수학/민정익      기계학습/권수태
10:30  리눅스운영체제/김영수  논리적문제해결2/송주환     기계학습/권수태     서비스러닝/이근호     확률과통계/고선우
12:00         점심시간          점심시간         점심시간          점심시간          점심시간
01:00  AI프로그래밍/김영수       딥러닝/고선우      딥러닝/고선우    인공지능기초/이근호  논리적문제해결1/민정익
02:30    확률과통계/고선우      AI수학/민정익  리눅스운영체제/김영수    AI알고리즘/권수태      영상이해/송주환
04:00     영상이해/송주환  논리적문제해결1/민정익         진로탐색  논리적문제해결2/송주환   AI프로그래밍/김영수

In [85]:
#2번씩만 나오도록 def로 설정

import pandas as pd
import random

# 과목 리스트를 만듭니다.
subjects = ['확률과통계/고선우', '딥러닝/고선우', 'AI알고리즘/권수태', '기계학습/권수태', 'AI수학/민정익', '논리적문제해결/민정익', '인공지능기초/이근호', '서비스러닝/이근호', '논리적문제해결/송주환', '영상이해/송주환', 'AI프로그래밍/김영수', '리눅스운영체제/김영수']

# 시간대 리스트를 만듭니다.
time_slots = ['09:00', '10:30', '12:00', '01:00', '02:30', '04:00']

# 중복 없이 과목을 선택하는 함수 정의
def choose_subject(subjects, chosen_subjects):
    subject = random.choice(subjects)
    subjects.remove(subject)
    chosen_subjects.append(subject)
    return subject

# 무작위로 시간표를 생성합니다.
timetable = pd.DataFrame(index=time_slots, columns=['월', '화', '수', '목', '금'])

chosen_subjects = []

for day in timetable.columns:
    for time in timetable.index:
        if time == '12:00':
            timetable.loc[time, day] = "점심시간"
        elif day == '수' and time == '04:00':
            timetable.loc[time, day] = "진로탐색"
        else:
            if not subjects:
                subjects = chosen_subjects.copy()
                chosen_subjects = []
            subject = choose_subject(subjects, chosen_subjects)
            timetable.loc[time, day] = subject

# 생성된 시간표를 출력합니다.
timetable

                월            화            수            목            금
09:00    AI수학/민정익     기계학습/권수태  AI프로그래밍/김영수    확률과통계/고선우   AI알고리즘/권수태
10:30   서비스러닝/이근호  리눅스운영체제/김영수   인공지능기초/이근호  AI프로그래밍/김영수     기계학습/권수태
12:00        점심시간         점심시간         점심시간         점심시간         점심시간
01:00    영상이해/송주환  논리적문제해결/송주환      딥러닝/고선우    서비스러닝/이근호     영상이해/송주환
02:30   확률과통계/고선우  논리적문제해결/민정익     AI수학/민정익  논리적문제해결/송주환   인공지능기초/이근호
04:00  AI알고리즘/권수태      딥러닝/고선우         진로탐색  논리적문제해결/민정익  리눅스운영체제/김영수

In [2]:
#하루 이상 간격두기

import pandas as pd
import random

# 과목 리스트를 만듭니다.
subjects = ['확률과통계/고선우', '딥러닝/고선우', 'AI알고리즘/권수태', '기계학습/권수태', 
            'AI수학/민정익', '논리적문제해결1/민정익', '인공지능기초/이근호', '서비스러닝/이근호', 
            '논리적문제해결2/송주환', '영상이해/송주환', 'AI프로그래밍/김영수', '리눅스운영체제/김영수']

# 시간대 리스트를 만듭니다.
time_slots = ['09:00', '10:30', '12:00', '01:00', '02:30', '04:00']

# 무작위로 시간표를 생성합니다.
timetable = pd.DataFrame(index=time_slots, columns=['월', '화', '수', '목', '금'])

# 중복 없이 과목을 선택하기 위한 set
subject_set = set()

# 이전에 선택된 과목을 기록하는 변수
prev_subject = None

for day in timetable.columns:
    for time in timetable.index:
        if time == '12:00':
            timetable.loc[time, day] = "점심시간"
        elif day == '수' and time == '04:00':
            timetable.loc[time, day] = "진로탐색"
        else:
            if not subject_set:  # set이 비어있을 경우, 모든 과목이 다 사용되었음
                subject_set = set(subjects)  # 모든 과목 다시 추가
            # 현재 선택된 과목과 이전 과목이 같은 경우 또는 하루 이상의 간격을 두지 않을 때
            while True:
                subject = random.choice(list(subject_set))
                if subject != prev_subject or prev_subject is None:
                    break
                    
            subject_set.remove(subject)
            timetable.loc[time, day] = subject
            prev_subject = subject

# 생성된 시간표를 출력합니다.
timetable

                  월           화             수             목            금
09:00   리눅스운영체제/김영수   확률과통계/고선우      기계학습/권수태    AI알고리즘/권수태    확률과통계/고선우
10:30     서비스러닝/이근호  인공지능기초/이근호  논리적문제해결1/민정익   리눅스운영체제/김영수     영상이해/송주환
12:00          점심시간        점심시간          점심시간          점심시간         점심시간
01:00  논리적문제해결2/송주환    영상이해/송주환     서비스러닝/이근호      기계학습/권수태  AI프로그래밍/김영수
02:30   AI프로그래밍/김영수    AI수학/민정익    인공지능기초/이근호  논리적문제해결1/민정익     AI수학/민정익
04:00    AI알고리즘/권수태     딥러닝/고선우          진로탐색  논리적문제해결2/송주환      딥러닝/고선우

In [1]:
#연강 없애기

import pandas as pd
import random

# 과목 및 교수님 리스트를 만듭니다.
subjects = ['확률과통계/고선우', '딥러닝/고선우', 'AI알고리즘/권수태', '기계학습/권수태', 
            'AI수학/민정익', '논리적문제해결1/민정익', '인공지능기초/이근호', '서비스러닝/이근호', 
            '논리적문제해결2/송주환', '영상이해/송주환', 'AI프로그래밍/김영수', '리눅스운영체제/김영수']

# 시간대 리스트를 만듭니다.
time_slots = ['09:00', '10:30', '12:00', '01:00', '02:30', '04:00']

# 무작위로 시간표를 생성합니다.
timetable = pd.DataFrame(index=time_slots, columns=['월', '화', '수', '목', '금'])

# 과목 및 교수님을 중복 없이 선택하기 위한 집합(set)
subject_set = set(subjects)
professors = {}  # 교수님별로 수업 스케줄을 추적할 딕셔너리

# 이전에 선택된 과목과 교수님을 기록하는 변수
prev_subject = None
prev_professor = None

for day in timetable.columns:
    for time in timetable.index:
        if time == '12:00':
            timetable.loc[time, day] = "점심시간"
        elif day == '수' and time == '04:00':
            timetable.loc[time, day] = "진로탐색"
        else:
            if not subject_set:  # set이 비어 있을 경우, 모든 과목을 다시 추가
                subject_set = set(subjects)
            # 현재 선택된 과목과 이전 과목이 같은 경우 또는 하루 이상의 간격을 두지 않을 때
            while True:
                subject = random.choice(list(subject_set))
                if subject != prev_subject or prev_subject is None:
                    break
            
            # 교수님을 추출
            professor = subject.split('/')[1]

            # 현재 선택된 교수님과 이전 교수님이 같은 경우 또는 하루 이상의 간격을 두지 않을 때
            while True:
                if professor != prev_professor or prev_professor is None:
                    break
                subject = random.choice(list(subject_set))
                professor = subject.split('/')[1]
            
            subject_set.remove(subject)
            timetable.loc[time, day] = subject
            prev_subject = subject
            prev_professor = professor

# 생성된 시간표를 출력합니다.
timetable

                  월             화          수             목             금
09:00      기계학습/권수태   AI프로그래밍/김영수  서비스러닝/이근호    AI알고리즘/권수태   AI프로그래밍/김영수
10:30      영상이해/송주환       딥러닝/고선우   AI수학/민정익    인공지능기초/이근호  논리적문제해결2/송주환
12:00          점심시간          점심시간       점심시간          점심시간          점심시간
01:00    인공지능기초/이근호   리눅스운영체제/김영수   기계학습/권수태  논리적문제해결1/민정익       딥러닝/고선우
02:30  논리적문제해결2/송주환    AI알고리즘/권수태  확률과통계/고선우      영상이해/송주환   리눅스운영체제/김영수
04:00     확률과통계/고선우  논리적문제해결1/민정익       진로탐색     서비스러닝/이근호      AI수학/민정익